display:
  default:
    display_title: 主
    display_options:
      exposed_form:
        options:
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      pager:
        options:
          tags:
            previous: '‹ 上一个'
            next: '下一个 ›'
            first: '« 首页'
            last: '末页 »'
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
