display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      pager:
        options:
          tags:
            previous: '‹ 上一个'
            next: '下一个 ›'
            first: '« 首页'
            last: '末页 »'
      fields:
        name:
          label: 作者
